ALTER TABLE pacientes
  ADD COLUMN IF NOT EXISTS sexo VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS seguro_medico VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS contacto_emergencia VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS telefono_emergencia VARCHAR(50) NULL;
